const actionType = {
    GET_SUPPLIER: 'GET_SUPPLIER',
    POST_SUPPLIER: 'POST_SUPPLIER',
    DELETE_SUPPLIER: 'DELETE_SUPPLIER',
    UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
    SEARCH_SUPPLIER: 'SEARCH_SUPPLIER',
};

export default actionType;